"""Add details and specifications to Product model

Revision ID: 4a8d4222ae60
Revises: 761f54427499
Create Date: 2025-04-27 22:39:58.712361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8d4222ae60'
down_revision = '761f54427499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specifications', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('specifications')
        batch_op.drop_column('details')

    # ### end Alembic commands ###
